http:
  middlewares:
    # CORS middleware
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "http://localhost:3000"
          - "https://kpt.local"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true

    # Security headers
    security:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # Rate limiting
    rate-limit:
      burst: 100
      average: 50

  # Роутинг теперь через Docker labels в docker-compose.yml
  # Переменные окружения используются в labels
