http:
  middlewares:
    # CORS middleware
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "http://localhost:3000"
          - "https://kpt.local"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true

    # Security headers
    security:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # Rate limiting
    rate-limit:
      burst: 100
      average: 50

  routers:
    # API router
    api:
      rule: "Host(`api.kpt.local`)"
      service: "api"
      middlewares:
        - cors
        - security
        - rate-limit

    # phpMyAdmin router
    phpmyadmin:
      rule: "Host(`phpmyadmin.kpt.local`)"
      service: "phpmyadmin"
      middlewares:
        - security

    # MinIO router
    minio:
      rule: "Host(`minio.kpt.local`)"
      service: "minio"
      middlewares:
        - security

    # MinIO Console router
    minio-console:
      rule: "Host(`minio-console.kpt.local`)"
      service: "minio-console"
      middlewares:
        - security

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://kpt-api-stg:3000"

    phpmyadmin:
      loadBalancer:
        servers:
          - url: "http://kpt-phpmyadmin-stg:80"

    minio:
      loadBalancer:
        servers:
          - url: "http://kpt-minio-stg:9000"

    minio-console:
      loadBalancer:
        servers:
          - url: "http://kpt-minio-stg:9001"
