api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: kpt-network

  file:
    filename: /dynamic/traefik.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: yarik.roterdamskiy@gmail.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog:
  format: json
